name: Build and Analyze
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: List files in directory
        run: ls -la

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # O la versión de PHP que necesites

      - name: Change to directory with composer.json
        run: cd ProyectoReverdecer/vistas/bower_components/select2/

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Cache Composer packages
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: sonar-scanner
